# Generated by Django 5.0.4 on 2024-09-16 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment_number', models.CharField(max_length=50, unique=True)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('python_t1', models.FloatField(blank=True, null=True)),
                ('python_t2', models.FloatField(blank=True, null=True)),
                ('python_t3', models.FloatField(blank=True, null=True)),
                ('python_t4', models.FloatField(blank=True, null=True)),
                ('full_stack_development_t1', models.FloatField(blank=True, null=True)),
                ('full_stack_development_t2', models.FloatField(blank=True, null=True)),
                ('full_stack_development_t3', models.FloatField(blank=True, null=True)),
                ('full_stack_development_t4', models.FloatField(blank=True, null=True)),
                ('discrete_mathematics_t1', models.FloatField(blank=True, null=True)),
                ('discrete_mathematics_t2', models.FloatField(blank=True, null=True)),
                ('discrete_mathematics_t3', models.FloatField(blank=True, null=True)),
                ('discrete_mathematics_t4', models.FloatField(blank=True, null=True)),
                ('theory_of_computation_t1', models.FloatField(blank=True, null=True)),
                ('theory_of_computation_t2', models.FloatField(blank=True, null=True)),
                ('theory_of_computation_t3', models.FloatField(blank=True, null=True)),
                ('theory_of_computation_t4', models.FloatField(blank=True, null=True)),
                ('computer_organization_and_architecture_t1', models.FloatField(blank=True, null=True)),
                ('computer_organization_and_architecture_t2', models.FloatField(blank=True, null=True)),
                ('computer_organization_and_architecture_t3', models.FloatField(blank=True, null=True)),
                ('computer_organization_and_architecture_t4', models.FloatField(blank=True, null=True)),
                ('attendance', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
