# Generated by Django 5.0.4 on 2024-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_studentdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='enrollment_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='roll_number',
            field=models.CharField(max_length=20),
        ),
    ]
