# Generated by Django 5.0.4 on 2024-09-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_facultydetails_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultydetails',
            old_name='department',
            new_name='subject',
        ),
        migrations.AddField(
            model_name='facultydetails',
            name='number',
            field=models.CharField(default='XXXXX XXXXX', max_length=100),
        ),
        migrations.AddField(
            model_name='facultydetails',
            name='short_name',
            field=models.CharField(default='XXX', max_length=100),
        ),
    ]
